version: 1
events:
  hostname: kafka
  port: 9092
  topic: events
  temperature:
    url: "http://storage:8090/storage/storage/temperature"
  motion:
    url: "http://storage:8090/storage/storage/motion"