urls:
  temperature_events: "http://storage:8090/storage/events/temperature"
  motion_events: "http://storage:8090/storage/events/motion"

file_paths:
  stats_file: "/app/data/stats.json"

logging:
  config_file: "processing_log_conf.yml"

scheduler:
  interval_seconds: 5